package sourcefile

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"log"
	"os"

	"github.com/src2crs/srcparser/nodes"
)

// SourceFile is a container that encapsulates a file path together with its source code
// and an abstract syntax tree from the ast package.
// It exposes methods to access the source code and parser results.
type SourceFile struct {
	root          nodes.BasicNode
	parser_errors error

	imports   nodes.ImportList
	functions []nodes.Function
}

// New creates a new SourceFile object from a file path and parses it.
func New(filepath string) *SourceFile {
	content, err := os.ReadFile(filepath)
	if err != nil {
		log.Fatal(err)
	}

	fileset := token.NewFileSet()
	file, errors := parser.ParseFile(fileset, filepath, content, parser.ParseComments)
	fileinfo := nodes.NewBasicNode(nodes.NewFileInfo(filepath, content, file), file)

	imports := []nodes.Import{}
	functions := []nodes.Function{}
	ast.Inspect(file, func(node ast.Node) bool {
		switch node := node.(type) {
		case *ast.ImportSpec:
			imports = append(imports, fileinfo.Import(node))
		case *ast.FuncDecl:
			functions = append(functions, fileinfo.Function(node))
		}
		return true
	})

	return &SourceFile{
		root:          fileinfo,
		parser_errors: errors,
		functions:     functions,
		imports:       imports,
	}
}

// HasParserErrors returns true if errors occurred during parsing.
func (sourcefile *SourceFile) HasParserErrors() bool {
	return sourcefile.parser_errors != nil
}

// Source returns the file's complete source code as a string.
func (sourcefile *SourceFile) Source() string {
	return sourcefile.root.Source()
}

// Section returns the file's complete source code between
// the positions given by begin and end.
// These positions are byte positions marking the bytes
// at the beginning and after the end of the source code, relative to the file.
func (sourcefile *SourceFile) Section(pos, end int) string {
	return sourcefile.root.Section(pos, end)
}

// ParserErrors returns the error string generated by the parser, if any.
// If no error occurred, the file name is returned
// with a message indicating that there were no errors.
func (sourcefile *SourceFile) ParserErrors() string {
	if sourcefile.HasParserErrors() {
		return sourcefile.parser_errors.Error()
	}
	return fmt.Sprintf("%s: no parser errors", sourcefile.root.Path())
}

// Function expects a function name and returns a nodes.Function
// representing the code that contains that function.
// Returns an invalid function object if no such function exists.
func (sourcefile *SourceFile) Function(name string) nodes.Function {
	for _, function := range sourcefile.functions {
		if function.Name() == name {
			return function
		}
	}
	return sourcefile.root.Function(nil)
}

// Imports returns a nodes.ImportList
// representing code that contains all imports from the
func (sourcefile *SourceFile) Imports() nodes.ImportList {
	return sourcefile.imports
}
